### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by AnkurShivani** [AuthorizeNet/sdk-ios#33]
When I run the project after pod install, I get below error. 

`dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: <Project_Path>
  Reason: image not found`

AuthorizeNet: 1.9.3
Cocoapods: 0.39.0
Xcode: 7.1.1
Deployment Target: 9.1

**Comment by ilitvinenko90** [comment]
+ Also have absolutely same issues. Does this issue fixed?

**Comment by Danbana** [comment]
Okay I just got past this, I had to do what is depicted in this screenshot
![screen shot 2016-03-24 at 3 36 13 pm 2](https://cloud.githubusercontent.com/assets/2365626/14033289/83a1d3e8-f1d6-11e5-8b32-104109c98ba6.png)

**Comment by AtheistP3ace** [comment]
I am having the same issue. Removing those 2 files did not work for me. Still get same error. Did you move to trash or just remove reference?

**Comment by brianmc** [comment]
Sample App should be working now.  Apologies for delays in getting this resolved, let us know if there are any additional issues.

**Comment by kenmhaggerty** [comment]
Hi – I'm having this exact issue with the Authorize.Net CocoaPod v1.9.8. Removing Anet_SDKTests.h/.m didn't solve the issue.

**Comment by Koteswar97** [comment]
hi, I am gettin gthe same issue
plz help me
